import * as esbuild from 'esbuild';

const isProd = process.env.BUILD === 'production';
const isWatch = process.argv.includes('--watch');

const banner = `/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source visit the plugins github repository
*/`;

const buildOptions = {
    entryPoints: ['src/main.ts'],
    bundle: true,
    outfile: 'main.js',
    platform: 'node',
    format: 'cjs',
    target: 'es2015',
    external: ['obsidian'],
    banner: {
        js: banner,
    },
    sourcemap: 'inline',
    sourcesContent: !isProd,
    minify: isProd,
    logLevel: 'info',
};

if (isWatch) {
    const context = await esbuild.context(buildOptions);
    await context.watch();
    console.log('Watching for changes...');
} else {
    await esbuild.build(buildOptions);
}
